<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\medicine;
use Faker\Factory as Faker;
class medicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        for ($i = 0; $i < 50; $i++) { // Creating 50 medicines, adjust the count as needed
            Medicine::create([
                'price' => $faker->randomFloat(2, 1, 1000), // Random price between 1 and 1000
                'quantity' => $faker->numberBetween(1, 100), // Random quantity between 1 and 100
                'code' => $faker->unique()->ean13, // Unique code generated by Faker
            ]);
        }
    }
}